---
# Test data is supposed to be verbatim, including errors. Exclude it from linting.
exclude: tests/integration/data

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files # We don't want huge files. (Cut down test data!)
        args: ['--maxkb=2000']
      - id: check-case-conflict # Don't allow files that differ by case sensitivity.
      - id: check-docstring-first # Avoid common error of code before docstring.
      - id: check-json # Check json file syntax
      - id: check-merge-conflict
      - id: check-symlinks # Symlinks that don't point to anything?
      - id: check-yaml # Check Yaml file syntax
      - id: debug-statements # Avoid commiting debug/breakpoints
      - id: fix-byte-order-marker # No UTF-8 byte order marks
      - id: mixed-line-ending # Don't allow mixed line endings
      - id: pretty-format-json
        args: ['--no-sort-keys', '--indent=4', '--autofix']
      - id: requirements-txt-fixer # Keep requirements files sorted.
      - id: trailing-whitespace # Auto remove trailing whitespace
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.9
      hooks:
      -   id: ruff
          args: [--fix, --show-fixes, --output-format, grouped]
      -   id: ruff-format
